import { useEffect } from "react";
import { Outlet, Link, createRootRoute, HeadContent, Scripts } from "@tanstack/react-router";

import appCss from "../styles.css?url";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/lib/auth";
import { startOfflineQueueWorker } from "@/lib/offlineQueue";
import { registerServiceWorker } from "@/lib/pwa";
import { I18nProvider } from "@/lib/i18n";
import InstallBanner from "@/components/InstallBanner";

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-7xl font-bold text-foreground">404</h1>
        <h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          The page you're looking for doesn't exist or has been moved.
        </p>
        <div className="mt-6">
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Go home
          </Link>
        </div>
      </div>
    </div>
  );
}

/**
 * Last line of defence: without this, a render error anywhere in the tree
 * unmounts the router and leaves a blank white page with no way back.
 */
function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="font-display text-2xl font-bold text-foreground">Something went wrong</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          The page hit an unexpected error. Trying again usually fixes it.
        </p>
        {import.meta.env.DEV && (
          <pre className="mt-4 max-h-40 overflow-auto rounded-lg bg-muted p-3 text-left text-xs text-muted-foreground">
            {error.message}
          </pre>
        )}
        <div className="mt-6 flex justify-center gap-3">
          <button
            onClick={reset}
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Try again
          </button>
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md border px-4 py-2 text-sm font-medium transition-colors hover:bg-muted"
          >
            Go home
          </Link>
        </div>
      </div>
    </div>
  );
}

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      // `viewport-fit=cover` is what makes env(safe-area-inset-*) resolve to
      // real values — without it the tab bar's bottom inset padding silently
      // collapses to 0 and sits under the iPhone home indicator.
      { name: "viewport", content: "width=device-width, initial-scale=1, viewport-fit=cover" },
      { name: "theme-color", content: "#006d39" },
      { name: "apple-mobile-web-app-capable", content: "yes" },
      { name: "apple-mobile-web-app-title", content: "FundiFast" },
      { name: "apple-mobile-web-app-status-bar-style", content: "black-translucent" },
      { name: "mobile-web-app-capable", content: "yes" },
      { title: "FundiFast — Hire trusted local fundis in Tanzania" },
      {
        name: "description",
        content:
          "FundiFast connects you with verified plumbers, electricians, carpenters and mechanics nearby in real time. Request a fundi, track them live, pay a fair price.",
      },
      { property: "og:title", content: "FundiFast — Hire trusted local fundis in Tanzania" },
      {
        property: "og:description",
        content:
          "FundiFast connects you with verified plumbers, electricians, carpenters and mechanics nearby in real time. Request a fundi, track them live, pay a fair price.",
      },
      { property: "og:type", content: "website" },
      { property: "og:site_name", content: "FundiFast" },
      { property: "og:locale", content: "en_TZ" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: "FundiFast — Hire trusted local fundis in Tanzania" },
      {
        name: "twitter:description",
        content:
          "FundiFast connects you with verified plumbers, electricians, carpenters and mechanics nearby in real time. Request a fundi, track them live, pay a fair price.",
      },
      // Served from our own origin (public/og-image.png, generated by
      // `npm run gen:icons`). The previous value pointed at a throwaway
      // Lovable preview bucket that would break every link preview the
      // moment that preview was recycled.
      { property: "og:image", content: "/og-image.png" },
      { property: "og:image:width", content: "1200" },
      { property: "og:image:height", content: "630" },
      { property: "og:image:alt", content: "FundiFast" },
      { name: "twitter:image", content: "/og-image.png" },
    ],
    links: [
      {
        rel: "stylesheet",
        href: appCss,
      },
      { rel: "manifest", href: "/manifest.webmanifest" },
      { rel: "icon", href: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { rel: "icon", href: "/favicon-192.png", sizes: "192x192", type: "image/png" },
      { rel: "apple-touch-icon", href: "/apple-touch-icon.png" },
      { rel: "stylesheet", href: "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" },
      { rel: "preconnect", href: "https://fonts.googleapis.com" },
      { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" },
      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@600;700&family=Inter:wght@400;500;600;700&display=swap",
      },
    ],
  }),
  shellComponent: RootShell,
  component: RootComponent,
  notFoundComponent: NotFoundComponent,
  errorComponent: ErrorComponent,
});

function RootShell({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function RootComponent() {
  useEffect(() => startOfflineQueueWorker(), []);
  useEffect(() => registerServiceWorker(), []);

  return (
    <I18nProvider>
      <AuthProvider>
        {/* Must render before Outlet: InstallBanner sits in normal document
            flow (not fixed) specifically so it pushes page content down
            instead of overlaying it — that only works if it's first. */}
        <InstallBanner />
        <Outlet />
        <Toaster position="top-center" richColors />
      </AuthProvider>
    </I18nProvider>
  );
}
