/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FundiSetupRouteImport } from './routes/fundi.setup'
import { Route as AppServiceRouteImport } from './routes/app.service'
import { Route as AppFindRouteImport } from './routes/app.find'
import { Route as AppDescribeRouteImport } from './routes/app.describe'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FundiSetupRoute = FundiSetupRouteImport.update({
  id: '/fundi/setup',
  path: '/fundi/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppFindRoute = AppFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AppRoute,
} as any)
const AppDescribeRoute = AppDescribeRouteImport.update({
  id: '/describe',
  path: '/describe',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/describe': typeof AppDescribeRoute
  '/app/find': typeof AppFindRoute
  '/app/service': typeof AppServiceRoute
  '/fundi/setup': typeof FundiSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/describe': typeof AppDescribeRoute
  '/app/find': typeof AppFindRoute
  '/app/service': typeof AppServiceRoute
  '/fundi/setup': typeof FundiSetupRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/describe': typeof AppDescribeRoute
  '/app/find': typeof AppFindRoute
  '/app/service': typeof AppServiceRoute
  '/fundi/setup': typeof FundiSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/admin/catalog'
    | '/admin/jobs'
    | '/admin/users'
    | '/app/describe'
    | '/app/find'
    | '/app/service'
    | '/fundi/setup'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/admin/catalog'
    | '/admin/jobs'
    | '/admin/users'
    | '/app/describe'
    | '/app/find'
    | '/app/service'
    | '/fundi/setup'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/admin/catalog'
    | '/admin/jobs'
    | '/admin/users'
    | '/app/describe'
    | '/app/find'
    | '/app/service'
    | '/fundi/setup'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  FundiSetupRoute: typeof FundiSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/fundi/setup': {
      id: '/fundi/setup'
      path: '/fundi/setup'
      fullPath: '/fundi/setup'
      preLoaderRoute: typeof FundiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/service': {
      id: '/app/service'
      path: '/service'
      fullPath: '/app/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/find': {
      id: '/app/find'
      path: '/find'
      fullPath: '/app/find'
      preLoaderRoute: typeof AppFindRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/describe': {
      id: '/app/describe'
      path: '/describe'
      fullPath: '/app/describe'
      preLoaderRoute: typeof AppDescribeRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDescribeRoute: typeof AppDescribeRoute
  AppFindRoute: typeof AppFindRoute
  AppServiceRoute: typeof AppServiceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDescribeRoute: AppDescribeRoute,
  AppFindRoute: AppFindRoute,
  AppServiceRoute: AppServiceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  FundiSetupRoute: FundiSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
